path: /Users/macbookpro/Cricket-Ball-Tracker/data # absolute path to dataset
test: test/images # relative path to test images
train: train/images # relative path to training images
val: val/images # relative path to validation images

# classes
names:
  0: cricketBall